const API='https://api3.geo.admin.ch/rest/services/api';
const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('fr-CH',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)+' CHF';const clean=s=>String(s||'').replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim();const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const trades={
 ferblanterie:{icon:'🔧',name:'Ferblanterie',sections:[['Travaux préparatoires · Démontage',['Démontage toiture','Eternit','Structure bois','Sous-couverture','Ferblanterie','Bâchage provisoire']],['Ferblanterie',['Ferblanterie cuivre pour toiture','Dépose et repose des chéneaux','Crochets de chéneaux','Raccordement des descentes','Tablettes de fonds de toit','Cheminées','Ventilations','Entourages des lucarnes','Dépose, rehausse cadre et repose 78/98 solaires']],['Pare-vapeur / isolations',['Pare-vapeur / isolations','Toutes découpes','Raccordement du pare-vapeur']],['Sous-couverture / contre-lattage',['Sous-couverture / contre-lattage','Étanchéité de sous-toiture soudée à chaud','Raccordements aux éléments traversants','Main d’œuvre démontage / évacuation','Compléments d’isolation 100 mm','Sous-couverture type Sarnafil TEX ou similaire']],['Lattage / couverture',['Lattage de soutien bois 27x60','Toutes découpes','Bavette 3 plis','Revêtement larmier','Revêtement de vire-vent','Couloir de rives','Gorge de raccordement et faîtage ventilé','Grille de ventilation','Garniture sous tablette']],['Charpente',['Pose isolation Bauder ECO S 125 mm','Pose 1er larmier','Pose calage de ventilation','Pose grille de ventilation','Pose 2ème larmier','Pose arrêt ventilation','Pièce de compensation bord de toit','Rehausse cadre Velux 78/98','Pose contre-lattage','Vire-vents 1er et 2ème','Menuiserie autour des lucarnes','Remplacement des éléments de charpente']]]},
 solaire:{icon:'☀️',name:'Installation photovoltaïque',sections:[['1. Admin / mise en service / support technique',['Administration, calepinage, simulation productible, annonces GRD/commune, Pronovo','Coordination technique avec DT','Mise en service, IAT, protocoles AC/DC et certification']],['2. Matériel photovoltaïque',['Panneaux photovoltaïques','Onduleur','Panneaux factices / raccord au bord de toiture']],['3. Système de montage',['Système de fixation intégré','Mise à terre de la structure','Système pare-neige']],['4. Câblage, protection DC, chemin de câble',['Dispositif de coupure DC avant onduleur et câblage PV','Protection surtension DC type I & II','Câble solaire souple 6 mm²','Prises et connecteurs','Protection des câbles DC','Tubes / gaines extérieures pour strings','Carottages en façade et rhabillage']],['5. Levage',['Transport et levage du matériel','Évacuation des déchets','Échafaudage, tour d’accès et sécurité en toiture']],['6. Raccordement AC',['Raccordement de l’onduleur au tableau','Équipotentiels / mise à terre','Création RCP / décompte et consommation interne','Routeur pour monitoring']]]},
 charpenterie:{icon:'🪵',name:'Charpenterie',sections:[['Charpenterie',['Intervention charpente']]]},couverture:{icon:'🏠',name:'Couverture',sections:[['Couverture',['Intervention couverture']]]},echafaudage:{icon:'🏗️',name:'Échafaudage',sections:[['Échafaudage',['Montage / démontage','Surface échafaudée','Protections périphériques','Location']]]}
};
let companyTrade=null,currentProject=null,measureTrade=null,addressHits={company:[],strom:[]},selected={company:null,strom:null};
const getProjects=()=>JSON.parse(localStorage.getItem('strom-projects-v1')||'[]');const putProjects=p=>localStorage.setItem('strom-projects-v1',JSON.stringify(p));
function show(id){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));$('#'+id).classList.add('active');scrollTo({top:0,behavior:'smooth'});if(id==='stromStart')renderSavedProjects()}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#companyPortal').onclick=()=>show('tradeStep');$('#stromPortal').onclick=()=>show('stromStart');
function defaultUnit(label){const s=label.toLowerCase();if(/panneaux photovolta|onduleur|crochet|descente|cheminée|ventilation|lucarne|velux|pièce/.test(s))return'pce';if(/surface|eternit|structure bois|sous-couverture|isolation|pare-vapeur|lattage|fixation/.test(s))return'm²';if(/chéneau|bavette|larmier|vire-vent|rives|faîtage|grille|pare-neige|câble|tube|gaine/.test(s))return'm';return'bloc'}
function template(key){const out=[];trades[key].sections.forEach(([section,items])=>items.forEach(label=>out.push({section,label,qty:'',unit:defaultUnit(label)})));return out}
Object.entries(trades).forEach(([key,t])=>{const d=document.createElement('button');d.className='trade';d.innerHTML=`<div class="icon">${t.icon}</div><b>${t.name}</b><p>Consulter le bordereau préparé par Ström.</p>`;d.onclick=()=>{companyTrade=key;selected.company=null;$('#companyAddress').value='';$('#companyFind').disabled=true;show('companySearch')};$('#tradeGrid').appendChild(d)});
async function searchAddresses(q){const p=new URLSearchParams({lang:'fr',searchText:q,type:'locations',sr:'2056',limit:'8',origins:'address'});const r=await fetch(`${API}/SearchServer?${p}`);if(!r.ok)throw Error('Recherche indisponible');const d=await r.json();return(d.results||[]).map(z=>({label:clean(z.attrs?.label),x:z.attrs?.x,y:z.attrs?.y})).filter(x=>x.label)}
function wireSearch(kind,inputSel,resultSel,buttonSel){let timer;const input=$(inputSel),box=$(resultSel),btn=$(buttonSel);input.oninput=()=>{selected[kind]=null;btn.disabled=true;clearTimeout(timer);const q=input.value.trim();if(q.length<3){box.classList.remove('open');return}timer=setTimeout(async()=>{try{addressHits[kind]=await searchAddresses(q);box.innerHTML=addressHits[kind].map((h,i)=>`<div class="address-result" data-i="${i}"><span class="pin">⌖</span><div><strong>${h.label}</strong><small>Adresse officielle suisse</small></div></div>`).join('');box.classList.toggle('open',!!addressHits[kind].length);box.querySelectorAll('.address-result').forEach(el=>el.onclick=()=>{selected[kind]=addressHits[kind][+el.dataset.i];input.value=selected[kind].label;box.classList.remove('open');btn.disabled=false})}catch{box.classList.remove('open')}},220)}}
wireSearch('company','#companyAddress','#companyAddressResults','#companyFind');wireSearch('strom','#stromAddress','#stromAddressResults','#createProject');
function projectKey(address){return clean(address).toLowerCase()}
$('#createProject').onclick=()=>{if(!selected.strom)return;const projects=getProjects(),key=projectKey(selected.strom.label);let p=projects.find(x=>x.key===key);if(!p){p={id:'P'+Date.now(),key,address:selected.strom.label,createdAt:new Date().toISOString(),trades:{}};projects.push(p);putProjects(projects)}currentProject=p;openStromProject()};
function renderSavedProjects(){const box=$('#savedProjects'),ps=getProjects();box.innerHTML=ps.length?`<h2>Projets préparés</h2><div class="project-list">${ps.map(p=>`<button class="project-item" data-id="${p.id}"><span>${p.address}</span><small>${Object.values(p.trades||{}).filter(x=>x.published).length} poste(s) publié(s)</small></button>`).join('')}</div>`:'<div class="empty-state">Aucun projet enregistré sur cet appareil pour le moment.</div>';box.querySelectorAll('.project-item').forEach(b=>b.onclick=()=>{currentProject=ps.find(p=>p.id===b.dataset.id);openStromProject()})}
function openStromProject(){if(!currentProject)return;$('#stromProjectTitle').textContent=currentProject.address;$('#stromProjectMeta').textContent='Préparez les quantités avant de rendre un poste accessible aux entreprises.';const g=$('#stromTradeGrid');g.innerHTML='';Object.entries(trades).forEach(([key,t])=>{const state=currentProject.trades?.[key];const b=document.createElement('button');b.className='trade';b.innerHTML=`<div class="icon">${t.icon}</div><b>${t.name}</b><p>${state?.published?'✓ Disponible aux entreprises':state?'Brouillon enregistré':'À préparer'}</p>`;b.onclick=()=>openMeasure(key);g.appendChild(b)});show('stromProject')}
function openMeasure(key){measureTrade=key;const state=currentProject.trades?.[key],data=state?.rows||template(key);$('#measureTitle').textContent=trades[key].name;$('#measureMeta').textContent=currentProject.address;renderMeasure(data);show('stromMeasure')}
function renderMeasure(data){const box=$('#measureRows');box.innerHTML='';let last='';data.forEach((r,i)=>{if(r.section!==last){const h=document.createElement('div');h.className='section-title';h.textContent=r.section;box.appendChild(h);last=r.section}const d=document.createElement('div');d.className='measure-row';d.dataset.i=i;d.innerHTML=`<input class="measure-label" value="${String(r.label).replace(/"/g,'&quot;')}"><input class="measure-qty" type="number" min="0" step="0.01" value="${r.qty}"><select class="measure-unit">${['m²','m','pce','bloc','forfait','h','kg'].map(u=>`<option ${u===r.unit?'selected':''}>${u}</option>`).join('')}</select><button class="remove-line" title="Supprimer">×</button>`;box.appendChild(d)})}
function collectMeasure(){return[...$('#measureRows').children].reduce((a,el)=>{if(!el.classList.contains('measure-row'))return a;const previous=[...el.parentNode.children].slice(0,[...el.parentNode.children].indexOf(el)).reverse().find(x=>x.classList.contains('section-title'));a.push({section:previous?.textContent||'Prestations',label:el.querySelector('.measure-label').value.trim(),qty:el.querySelector('.measure-qty').value,unit:el.querySelector('.measure-unit').value});return a},[]).filter(r=>r.label)}
$('#measureRows').onclick=e=>{if(e.target.classList.contains('remove-line'))e.target.closest('.measure-row').remove()};$('#addMeasureRow').onclick=()=>{const data=collectMeasure();data.push({section:'Prestations complémentaires',label:'Nouvelle prestation',qty:'',unit:'pce'});renderMeasure(data)};
function saveMeasure(published){const rows=collectMeasure();if(published&&rows.some(r=>r.qty===''||num(r.qty)===null)){$('#measureStatus').textContent='Complétez toutes les quantités avant de rendre le bordereau disponible.';return}const ps=getProjects(),p=ps.find(x=>x.id===currentProject.id);p.trades[measureTrade]={rows,published,updatedAt:new Date().toISOString()};putProjects(ps);currentProject=p;$('#measureStatus').textContent=published?'✓ Bordereau validé. Les entreprises peuvent maintenant le consulter.':'✓ Brouillon enregistré.';if(published)setTimeout(openStromProject,700)}$('#saveDraft').onclick=()=>saveMeasure(false);$('#publishMeasure').onclick=()=>saveMeasure(true);
$('#companyFind').onclick=()=>{if(!selected.company||!companyTrade)return;const p=getProjects().find(x=>x.key===projectKey(selected.company.label)),state=p?.trades?.[companyTrade];if(!p||!state?.published){$('#companyStatus').textContent=`Aucun bordereau ${trades[companyTrade].name} n’est encore disponible pour cette adresse.`;return}currentProject=p;openCompanyQuote(state)};
function openCompanyQuote(state){$('#companyProjectTitle').textContent=trades[companyTrade].name;$('#companyProjectMeta').textContent=currentProject.address;const box=$('#companyRows');box.innerHTML='';let last='';state.rows.forEach((r,i)=>{if(r.section!==last){const h=document.createElement('div');h.className='section-title';h.textContent=r.section;box.appendChild(h);last=r.section}const d=document.createElement('div');d.className='row';d.dataset.i=i;d.innerHTML=`<div class="designation">${r.label}</div><div class="locked-qty">🔒 ${r.qty}</div><div class="locked-unit">🔒 ${r.unit}</div><input class="unit-price" type="number" min="0" step="0.01" placeholder="CHF"><span class="amount">0.00 CHF</span>`;d.querySelector('input').oninput=()=>recalcCompany();box.appendChild(d)});recalcCompany();show('companyQuote')}
function recalcCompany(){let total=0;$('#companyRows').querySelectorAll('.row').forEach(r=>{const q=num(r.querySelector('.locked-qty').textContent.replace('🔒','').trim())||0,p=num(r.querySelector('.unit-price').value)||0,v=q*p;total+=v;r.querySelector('.amount').textContent=money(v)});$('#companyTotal').textContent=money(total)}
$('#companyReview').onclick=()=>{let total=0,lines=[];$('#companyRows').querySelectorAll('.row').forEach(r=>{const label=r.querySelector('.designation').textContent,q=r.querySelector('.locked-qty').textContent.replace('🔒','').trim(),u=r.querySelector('.locked-unit').textContent.replace('🔒','').trim(),p=num(r.querySelector('.unit-price').value)||0,v=(num(q)||0)*p;total+=v;lines.push(`<tr><td>${label}</td><td>${q} ${u}</td><td>${money(p)}</td><td>${money(v)}</td></tr>`)});$('#companySummary').innerHTML=`<div class="summary-head"><div><span>Projet</span><strong>${currentProject.address}</strong></div><div><span>Poste</span><strong>${trades[companyTrade].name}</strong></div><div><span>Entreprise</span><strong>${$('#companyName').value||'Non renseigné'}</strong></div></div><table><thead><tr><th>Prestation</th><th>Quantité</th><th>Prix unitaire</th><th>Total</th></tr></thead><tbody>${lines.join('')}</tbody></table><div class="total"><span>Total HT</span><strong>${money(total)}</strong></div>`;show('companyReviewStep')};$('#sendBtn').onclick=()=>{$('#sendStatus').textContent='✓ Offre prête. La transmission serveur sera branchée avec le futur backend Ström.'};
