const project={name:'PPE Chalet Thomas',address:'Ch. des Pierrailles 12, 1659 Rougemont',owner:'PPE Chalet Thomas'};
const trades={
 ferblanterie:{icon:'🔧',name:'Ferblanterie',desc:'Ferblanterie et revêtements liés à la toiture photovoltaïque.',info:[['Adresse',project.address],['Surface toiture','400 m²'],['Surface isolation','320 m²'],['Sous-couverture / contre-lattage','430 m²'],['Bavette 3 plis','59 m'],['Revêtement larmier','75 m'],['Revêtement vire-vent','43 m'],['Couloirs de rives','50 m'],['Faîtage / gorge raccordement','57 m'],['Velux 78/98','6 pièces']],sections:[{title:'Travaux préparatoires · Démontage',items:[['Démontage toiture',400,'m²'],['Eternit',400,'m²'],['Structure bois',400,'m²'],['Sous-couverture',400,'m²'],['Ferblanterie existante',400,'m²'],['Bâchage provisoire',400,'m²']]},{title:'Ferblanterie',items:[['Ferblanterie cuivre pour toiture',1,'pce'],['Dépose et repose des chéneaux',1,'forfait'],['Crochets de chéneaux',1,'forfait'],['Raccordement des descentes',1,'forfait'],['Tablettes de fonds de toit',1,'forfait'],['Cheminées / ventilations / lucarnes',1,'forfait'],['Dépose, rehausse cadre et repose Velux 78/98',6,'pce']]},{title:'Pare-vapeur / isolations',items:[['Pare-vapeur / isolations',320,'m²']]},{title:'Sous-couverture / contre-lattage',items:[['Sous-couverture / contre-lattage',430,'m²']]},{title:'Lattage / couverture',items:[['Lattage de soutien bois 27x60',400,'m²'],['Bavette 3 plis',59,'m'],['Revêtement larmier',75,'m'],['Revêtement de vire-vent',43,'m'],['Couloir de rives',50,'m'],['Gorge de raccordement / faîtage ventilé',57,'m'],['Grille de ventilation',57,'m'],['Garniture sous tablette',1,'bloc']]}]},
 charpenterie:{icon:'🪵',name:'Charpenterie',desc:'Structure bois, isolation, ventilation et contre-lattage.',info:[['Adresse',project.address],['Surface toiture','400 m²'],['Structure','Charpente bois'],['Velux 78/98','6 pièces'],['Vire-vents','43 m']],sections:[{title:'Charpente',items:[['Pose isolation type Bauder Eco S 125 mm',400,'m²'],['Pose 1er larmier',36,'m'],['Calage de ventilation',70,'pce'],['Grille de ventilation',36,'m'],['Pose 2ème larmier',36,'m'],['Arrêt ventilation',36,'m'],['Pièce de compensation bord de toit',1,'forfait'],['Rehausse cadre Velux 78/98, raccords et garniture',6,'pce'],['Pose contre-lattage',400,'m²'],['Vire-vents 1er et 2ème',43,'m'],['Menuiserie autour des lucarnes',1,'bloc']]}]},
 couverture:{icon:'🏠',name:'Couverture',desc:'Revêtement, dépose et travaux de couverture.',info:[['Adresse',project.address],['Surface toiture','400 m²'],['Sous-couverture','430 m²']],sections:[{title:'Revêtements de toiture',items:[['Dépose couverture',400,'m²'],['Sous-couverture',430,'m²'],['Lattage de soutien',400,'m²']]}]},
 echafaudage:{icon:'🏗️',name:'Échafaudage',desc:'Montage, protections, accès et location.',info:[['Adresse',project.address],['Surface toiture','400 m²']],sections:[{title:'Échafaudage',items:[['Montage / démontage',1,'forfait'],['Location',1,'forfait'],['Protections',1,'forfait']]}]}
};
let current=null,rows=[];const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('fr-CH',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)+' CHF';
function page(n){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$('#step'+n).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
Object.entries(trades).forEach(([k,t])=>{const d=document.createElement('div');d.className='trade';d.innerHTML=`<div class="icon">${t.icon}</div><b>${t.name}</b><p>${t.desc}</p>`;d.onclick=()=>selectTrade(k);$('#tradeGrid').appendChild(d)});
function selectTrade(k){current=k;const t=trades[k];$('#projectTitle').textContent=`${project.name} · ${t.name}`;$('#tradeDescription').textContent=project.address;$('#formTitle').textContent=`Soumission ${t.name}`;$('#technicalInfo').innerHTML=t.info.map(([a,b])=>`<div class="info"><span>${a}</span><strong>${b}</strong></div>`).join('');rows=[];t.sections.forEach((section,si)=>section.items.forEach(item=>rows.push({section:section.title,sectionIndex:si,label:item[0],qty:item[1],unit:item[2],price:0,locked:true})));renderRows();page(2)}
function renderRows(){const box=$('#quoteRows');box.innerHTML='';let last='';rows.forEach((r,i)=>{if(r.section!==last){const h=document.createElement('div');h.className='section-title';h.textContent=r.section;box.appendChild(h);last=r.section}const d=document.createElement('div');d.className='row';d.innerHTML=`<div class="designation">${r.label}</div><div class="locked-qty">${r.qty}</div><div class="locked-unit">${r.unit}</div><input type="number" min="0" step="0.01" value="${r.price||''}" placeholder="CHF" data-f="price"><span class="amount">${money(r.qty*r.price)}</span>${r.locked?'':'<button class="remove">×</button>'}`;const inp=d.querySelector('input');inp.oninput=()=>{r.price=Number(inp.value);d.querySelector('.amount').textContent=money(r.qty*r.price);renderTotal()};const remove=d.querySelector('.remove');if(remove)remove.onclick=()=>{rows.splice(i,1);renderRows()};box.appendChild(d)});renderTotal()}
function renderTotal(){$('#grandTotal').textContent=money(rows.reduce((s,r)=>s+r.qty*r.price,0))}
$('#addRow').onclick=()=>{const label=prompt('Nom de la prestation complémentaire :');if(!label)return;const qty=Number(prompt('Quantité :','1'));if(!Number.isFinite(qty)||qty<=0)return;const unit=prompt('Unité (m², m, pce, forfait...) :','pce')||'pce';rows.push({section:'Prestations complémentaires',label,qty,unit,price:0,locked:false});renderRows()};
document.querySelectorAll('.back').forEach(b=>b.onclick=()=>page(Number(b.dataset.back)));
$('#reviewBtn').onclick=()=>{const t=trades[current],total=rows.reduce((s,r)=>s+r.qty*r.price,0);const company=$('#companyName').value||'Non renseigné';$('#summary').innerHTML=`<div class="summary-head"><div><span>Projet</span><strong>${project.name}</strong></div><div><span>Poste</span><strong>${t.name}</strong></div><div><span>Entreprise</span><strong>${company}</strong></div></div><table><thead><tr><th>Prestation</th><th>Quantité</th><th>Prix unitaire</th><th>Total</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.label}</td><td>${r.qty} ${r.unit}</td><td>${money(r.price)}</td><td>${money(r.qty*r.price)}</td></tr>`).join('')}</tbody></table><div class="total"><span>Total HT</span><strong>${money(total)}</strong></div>`;page(3)};
$('#sendBtn').onclick=()=>{const payload={project,trade:trades[current].name,company:{name:$('#companyName').value,contact:$('#contactName').value,email:$('#email').value,vat:$('#vat').value},technicalData:Object.fromEntries(trades[current].info),lines:rows,notes:$('#notes').value,total:rows.reduce((s,r)=>s+r.qty*r.price,0),createdAt:new Date().toISOString(),source:'Climacy / Ström'};localStorage.setItem('strom-last-quote',JSON.stringify(payload));$('#sendStatus').textContent='✓ Soumission enregistrée. Le branchement au système Ström sera ajouté à cette étape.'};
